/**
 * CS2 官方 callout 名 → 中文名映射表。
 *
 * 来源：79 场 demo（pro 24 + NJU 55）的 `lastPlaceName` 词表 + 社区约定。
 * 定位：供 Area v1 / 动线 / 展示层消费，不含坐标与路由逻辑。
 * 待核验：部分 callout 可能有更精确的社区叫法，本表为初稿。
 */
export const CALLOUT_NAME_CN = {
  de_ancient: {
    BombsiteA: "A包",
    BombsiteB: "B包",
    Middle: "中路",
    Outside: "匪口",
    SideEntrance: "黑屋",
    Alley: "底线",
    TSideUpper: "跳台",
    TSideLower: "B小",
    CTSpawn: "警家",
    SideHall: "甜甜圈",
    MainHall: "A厅",
    Ruins: "B外",
    House: "VIP",
    Ramp: "B坡",
    TSpawn: "匪家",
    Tunnel: "隧道",
    Water: "水路",
    TopofMid: "中远",
  },

  de_anubis: {
    BombsiteB: "B包",
    Canal: "水下",
    Middle: "中路",
    Bridge: "中桥",
    OutsideLong: "B外",
    BombsiteA: "A包",
    Ruins: "B外",
    Connector: "黑屋",
    PalaceInterior: "B连",
    Main: "A厅",
    Walkway: "A连",
    BackofB: "B包台上",
    TSpawn: "匪家",
    Street: "街道",
    Heaven: "天堂",
    MidDoors: "中门",
    TSideUpper: "匪跳",
    CTSideUpper: "警家",
    Alley: "警家",
    Bricks: "B连阳光房",
    Fountain: "喷泉",
    TStairs: "匪梯",
    LowerTunnel: "警家隧道",
    CTSpawn: "警家后",
    TunnelStairs: "隧道楼梯",
    SnipersNest: "警家狙位",
    Tunnel: "隧道",
    Water: "警家水下",
  },

  de_dust2: {
    BombsiteB: "B包",
    LongDoors: "A门",
    LongA: "A大",
    MidDoors: "中门",
    UpperTunnel: "B洞",
    TopofMid: "中远匪口",
    OutsideLong: "A门外",
    UnderA: "警家",
    CTSpawn: "警家",
    Catwalk: "A小",
    ExtendedA: "A小过点",
    ShortStairs: "A小楼梯",
    Middle: "中路",
    BombsiteA: "A包",
    TSpawn: "匪家",
    LowerTunnel: "B1",
    BDoors: "B门",
    ARamp: "A斜坡",
    OutsideTunnel: "B洞外",
    Pit: "大坑",
    TunnelStairs: "B洞楼梯",
    Hole: "狗洞",
    Side: "大坑平台",
    TRamp: "后花",
  },

  de_inferno: {
    Banana: "香蕉道",
    BombsiteB: "B包",
    BombsiteA: "A包",
    Apartments: "二楼",
    Middle: "中路",
    CTSpawn: "警家",
    TopofMid: "中路",
    Arch: "拱门",
    Ruins: "警家教堂",
    Pit: "大坑",
    SecondMid: "侧道",
    TRamp: "匪口",
    TSpawn: "匪家",
    Balcony: "阳台",
    LowerMid: "匪口",
    Library: "书房",
    BackAlley: "匪二楼",
    Underpass: "下水道",
    Quad: "马鹏",
    Deck: "匪二阳台",
    Bridge: "匪桥",
    Upstairs: "匪二楼",
    Graveyard: "墓地",
    Kitchen: "厨房",
  },

  de_mirage: {
    BombsiteA: "A包",
    CTSpawn: "警家",
    BombsiteB: "B包",
    PalaceInterior: "A二楼",
    Middle: "中路",
    TopofMid: "中远/匪口",
    Catwalk: "B小",
    Apartments: "B二楼",
    Underpass: "下水道",
    TSpawn: "匪家",
    PalaceAlley: "A1",
    Connector: "拱门",
    SideAlley: "匪口",
    BackAlley: "B二楼",
    Jungle: "Jungle",
    Shop: "超市",
    TRamp: "A1",
    SnipersNest: "VIP",
    Truck: "白车",
    House: "匪二楼",
    Stairs: "跳台",
    Ladder: "黑屋",
    Scaffolding: "A2上下",
  },

  de_nuke: {
    Outside: "外场",
    BombsiteA: "A包",
    Ramp: "铁板",
    Lobby: "匪厅",
    Tunnels: "K1地下",
    BombsiteB: "B包",
    TSpawn: "匪家",
    Mini: "正门",
    Squeaky: "铁门房",
    Control: "链接",
    Garage: "大仓",
    Rafters: "三楼横梁",
    Hut: "黄房",
    Vending: "链接",
    Heaven: "三楼",
    Admin: "铁板三楼下",
    CTSpawn: "警家",
    Secret: "K1",
    Trophy: "奖杯房",
    HutRoof: "黄房顶",
    Hell: "三楼下",
    Roof: "屋顶",
    Silo: "山上",
    Vents: "管道",
    Catwalk: "外场三楼",
    Decon: "死门",
    Crane: "",
    Observation: "控制室",
    LockerRoom: "更衣室",
  },

  de_overpass: {
    LowerPark: "A小厕所",
    Water: "工地",
    BombsiteA: "A包",
    BombsiteB: "B包",
    UpperPark: "A大厕所",
    Canal: "长管",
    Fountain: "喷泉",
    Tunnels: "下水道",
    Connector: "下水道",
    Walkway: "ABC",
    Construction: "B小",
    TSpawn: "匪家",
    Alley: "匪家B外",
    SnipersNest: "B二楼",
    UnderA: "一层",
    BackofA: "垃圾桶",
    Pipe: "短管",
    Lobby: "银行",
    Playground: "游乐园",
    Restroom: "厕所",
    TStairs: "匪楼梯",
    Bridge: "桥",
    Stairs: "楼梯",
    StorageRoom: "银行",
    SideAlley: "匪家保枪位",
  },
} as const;

/** 所有已标定的地图名。 */
export const CALLOUT_MAPS = Object.keys(CALLOUT_NAME_CN) as ReadonlyArray<
  keyof typeof CALLOUT_NAME_CN
>;
