/**
 * CS2 官方 callout 名 → 中文名映射表。
 *
 * 来源：79 场 demo（pro 24 + NJU 55）的 `lastPlaceName` 词表 + 社区约定。
 * 定位：供 Area v1 / 动线 / 展示层消费，不含坐标与路由逻辑。
 * 待核验：部分 callout 可能有更精确的社区叫法，本表为初稿。
 */
export const CALLOUT_NAME_CN = {
  de_ancient: {
    BombsiteA: "A包点",
    BombsiteB: "B包点",
    Middle: "中路",
    Outside: "A外",
    SideEntrance: "B小/连接",
    Alley: "底线",
    TSideUpper: "跳台",
    TSideLower: "B门外",
    CTSpawn: "警家",
    SideHall: "A小/甜甜圈",
    MainHall: "A厅",
    Ruins: "遗迹",
    House: "黑屋/猎豹房",
    Ramp: "B斜坡",
    TSpawn: "匪家",
    Tunnel: "隧道",
    Water: "水路",
    TopofMid: "VIP/中门上",
  },

  de_anubis: {
    BombsiteB: "B包点",
    Canal: "水渠",
    Middle: "中路",
    Bridge: "桥",
    OutsideLong: "B门外/长廊外",
    BombsiteA: "A包点",
    Ruins: "废墟",
    Connector: "连接",
    PalaceInterior: "殿内/宫殿",
    Main: "A正门",
    Walkway: "走廊/平台",
    BackofB: "B后点",
    TSpawn: "匪家",
    Street: "街道",
    Heaven: "天堂",
    MidDoors: "中门",
    TSideUpper: "匪上层",
    CTSideUpper: "警上层",
    Alley: "小巷",
    Bricks: "砖墙",
    Fountain: "喷泉",
    TStairs: "匪楼梯",
    LowerTunnel: "下水道",
    CTSpawn: "警家",
    TunnelStairs: "隧道楼梯",
    SnipersNest: "狙位",
    Tunnel: "隧道",
    Water: "水下",
  },

  de_dust2: {
    BombsiteB: "B包点",
    LongDoors: "A门/长门",
    LongA: "A大",
    MidDoors: "中门",
    UpperTunnel: "B洞/上层隧道",
    TopofMid: "中远/匪口",
    OutsideLong: "A门外/长门外",
    UnderA: "A小楼梯下",
    CTSpawn: "警家",
    Catwalk: "A小",
    ExtendedA: "A平台/警家过点",
    ShortStairs: "A小楼梯",
    Middle: "中路",
    BombsiteA: "A包点",
    TSpawn: "匪家",
    LowerTunnel: "B1/下层隧道",
    BDoors: "B门",
    ARamp: "A斜坡",
    OutsideTunnel: "B洞外",
    Pit: "大坑",
    TunnelStairs: "洞口楼梯",
    Hole: "狗洞",
    Side: "侧道/蓝车侧",
    TRamp: "匪家斜坡",
  },

  de_inferno: {
    Banana: "香蕉道",
    BombsiteB: "B包点",
    BombsiteA: "A包点",
    Apartments: "二楼/公寓",
    Middle: "中路",
    CTSpawn: "警家",
    TopofMid: "中路顶/中路尽头",
    Arch: "拱门",
    Ruins: "后花园/废墟",
    Pit: "大坑",
    SecondMid: "侧道/二中",
    TRamp: "匪口斜坡",
    TSpawn: "匪家",
    Balcony: "阳台",
    LowerMid: "下中路",
    Library: "书房",
    BackAlley: "后巷",
    Underpass: "下水道",
    Quad: "四箱/小坑",
    Deck: "桥",
    Bridge: "桥",
    Upstairs: "楼梯上",
    Graveyard: "墓地",
    Kitchen: "厨房",
  },

  de_mirage: {
    BombsiteA: "A包点",
    CTSpawn: "警家",
    BombsiteB: "B包点",
    PalaceInterior: "二楼/宫殿内",
    Middle: "中路",
    TopofMid: "中远/匪口",
    Catwalk: "B小",
    Apartments: "B二楼",
    Underpass: "下水道",
    TSpawn: "匪家",
    PalaceAlley: "二楼外/宫殿外",
    Connector: "拱门/连接",
    SideAlley: "侧巷/沙袋草车",
    BackAlley: "B二楼后巷",
    Jungle: "VIP/Jungle",
    Shop: "超市",
    TRamp: "A1/A门",
    SnipersNest: "VIP/狙位",
    Truck: "货车",
    House: "屋檐/匪二楼外",
    Stairs: "长箱/楼梯",
    Ladder: "跳台",
    Scaffolding: "脚手架/二楼外架",
  },

  de_nuke: {
    Outside: "外场",
    BombsiteA: "A包点",
    Ramp: "K1/斜坡",
    Lobby: "匪厅",
    Tunnels: "管道/地下通道",
    BombsiteB: "B包点",
    TSpawn: "匪家",
    Mini: "铁门房/小黄房",
    Squeaky: "铁门",
    Control: "控制室",
    Garage: "仓库/车库",
    Rafters: "铁板/黄房二层",
    Hut: "黄房",
    Vending: "售货机",
    Heaven: "三楼/天堂",
    Admin: "办公室/管理室",
    CTSpawn: "警家",
    Secret: "山上/水箱/Secret",
    Trophy: "奖杯房",
    HutRoof: "黄房顶",
    Hell: "地狱",
    Roof: "屋顶",
    Silo: "狙击位/红箱",
    Vents: "管道口/通风管",
    Catwalk: "外场铁板/猫道",
    Decon: "解毒室",
    Crane: "吊车/Crane",
    Observation: "观察室",
    LockerRoom: "更衣室",
  },

  de_overpass: {
    LowerPark: "下公园/长椅",
    Water: "水下",
    BombsiteA: "A包点",
    BombsiteB: "B包点",
    UpperPark: "上公园",
    Canal: "下水道/运河",
    Fountain: "喷泉",
    Tunnels: "匪洞/隧道",
    Connector: "连接",
    Walkway: "桥/走道",
    Construction: "工地",
    TSpawn: "匪家",
    Alley: "小巷/匪B外",
    SnipersNest: "狙位",
    UnderA: "A下/厕所中段",
    BackofA: "A后/包点后",
    Pipe: "管道",
    Lobby: "银行大厅/大厅",
    Playground: "游乐园",
    Restroom: "厕所",
    TStairs: "匪楼梯",
    Bridge: "桥",
    Stairs: "楼梯",
    StorageRoom: "储藏室",
    SideAlley: "侧巷",
  },
} as const;

/** 所有已标定的地图名。 */
export const CALLOUT_MAPS = Object.keys(CALLOUT_NAME_CN) as ReadonlyArray<
  keyof typeof CALLOUT_NAME_CN
>;
