/** callout 条目：中文名 + 可选战术倾向。 */
export interface CalloutNameEntry {
  cn: string;
  /** 战术倾向：首元素为该位置在阵容中的主要方向。取 tendency[0] 参与区域人数统计。 */
  tendency?: Array<"a" | "b" | "mid">;
}

/** 取 callout 的中文名。 */
export function calloutCn(mapName: string, id: string): string {
  return CALLOUT_DICT[mapName]?.[id]?.cn ?? "";
}

/** 取 callout 的战术倾向。 */
export function calloutTendency(mapName: string, id: string): Array<"a" | "b" | "mid"> | undefined {
  return CALLOUT_DICT[mapName]?.[id]?.tendency;
}

/**
 * CS2 官方 callout 名 → 中文名 + 战术倾向映射表。
 *
 * 来源：79 场 demo（pro 24 + NJU 55）的 `lastPlaceName` 词表 + 社区约定。
 * 定位：供 Area v1 / 动线 / 展示层消费，不含坐标与路由逻辑。
 * 待核验：部分 callout 可能有更精确的社区叫法，本表为初稿。
 */
export const CALLOUT_DICT: Record<string, Record<string, CalloutNameEntry>> = {
  de_ancient: {
    BombsiteA: { cn: "A包", tendency: ["a"] },
    BombsiteB: { cn: "B包", tendency: ["b"] },
    Middle: { cn: "中路", tendency: ["mid"] },
    Outside: { cn: "匪口", tendency: ["a", "mid"] },
    SideEntrance: { cn: "黑屋", tendency: ["b"] },
    Alley: { cn: "底线", tendency: ["b"] },
    TSideUpper: { cn: "跳台", tendency: ["mid", "b"] },
    TSideLower: { cn: "B小", tendency: ["b"] },
    CTSpawn: { cn: "警家", tendency: ["a"] },
    SideHall: { cn: "甜甜圈", tendency: ["a"] },
    MainHall: { cn: "A厅", tendency: ["a"] },
    Ruins: { cn: "B外", tendency: ["b"] },
    House: { cn: "VIP", tendency: ["mid"] },
    Ramp: { cn: "B坡", tendency: ["b"] },
    TSpawn: { cn: "匪家" },
    Tunnel: { cn: "隧道", tendency: ["b"] },
    Water: { cn: "水路", tendency: ["b"] },
    TopofMid: { cn: "中远", tendency: ["mid"] },
  },

  de_anubis: {
    BombsiteB: { cn: "B包", tendency: ["b"] },
    Canal: { cn: "水下", tendency: ["a", "b"] },
    Middle: { cn: "中路", tendency: ["mid"] },
    Bridge: { cn: "中桥", tendency: ["mid"] },
    OutsideLong: { cn: "B外", tendency: ["b"] },
    BombsiteA: { cn: "A包", tendency: ["a"] },
    Ruins: { cn: "B外", tendency: ["b"] },
    Connector: { cn: "黑屋", tendency: ["b"] },
    PalaceInterior: { cn: "B连", tendency: ["b"] },
    Main: { cn: "A厅", tendency: ["a"] },
    Walkway: { cn: "A连", tendency: ["a"] },
    BackofB: { cn: "B包台上", tendency: ["b"] },
    TSpawn: { cn: "匪家" },
    Street: { cn: "街道", tendency: ["a"] },
    Heaven: { cn: "天堂", tendency: ["a"] },
    MidDoors: { cn: "中门", tendency: ["mid"] },
    TSideUpper: { cn: "匪跳", tendency: ["a"] },
    CTSideUpper: { cn: "警家" },
    Alley: { cn: "警家", tendency: ["b"] },
    Bricks: { cn: "B连阳光房", tendency: ["b"] },
    Fountain: { cn: "喷泉", tendency: ["a"] },
    TStairs: { cn: "匪梯", tendency: ["a", "b"] },
    LowerTunnel: { cn: "警家隧道", tendency: ["b"] },
    CTSpawn: { cn: "警家后" },
    TunnelStairs: { cn: "隧道楼梯", tendency: ["a"] },
    SnipersNest: { cn: "警家狙位", tendency: ["b"] },
    Tunnel: { cn: "隧道", tendency: ["a"] },
    Water: { cn: "警家水下", tendency: ["a", "b"] },
  },

  de_dust2: {
    BombsiteB: { cn: "B包", tendency: ["b"] },
    LongDoors: { cn: "A门", tendency: ["a"] },
    LongA: { cn: "A大", tendency: ["a"] },
    MidDoors: { cn: "中门", tendency: ["mid"] },
    UpperTunnel: { cn: "B洞", tendency: ["b"] },
    TopofMid: { cn: "中远匪口", tendency: ["mid"] },
    OutsideLong: { cn: "A门外", tendency: ["a"] },
    UnderA: { cn: "警家", tendency: ["a"] },
    CTSpawn: { cn: "警家", tendency: ["mid", "a"] },
    Catwalk: { cn: "A小", tendency: ["a", "mid"] },
    ExtendedA: { cn: "A小过点", tendency: ["a"] },
    ShortStairs: { cn: "A小楼梯", tendency: ["a"] },
    Middle: { cn: "中路", tendency: ["mid"] },
    BombsiteA: { cn: "A包", tendency: ["a"] },
    TSpawn: { cn: "匪家" },
    LowerTunnel: { cn: "B1", tendency: ["mid"] },
    BDoors: { cn: "B门", tendency: ["b"] },
    ARamp: { cn: "A斜坡", tendency: ["a"] },
    OutsideTunnel: { cn: "B洞外", tendency: ["b"] },
    Pit: { cn: "大坑", tendency: ["a"] },
    TunnelStairs: { cn: "B洞楼梯", tendency: ["b"] },
    Hole: { cn: "狗洞", tendency: ["b"] },
    Side: { cn: "大坑平台", tendency: ["a"] },
    TRamp: { cn: "后花", tendency: ["b"] },
  },

  de_inferno: {
    Banana: { cn: "香蕉道", tendency: ["b"] },
    BombsiteB: { cn: "B包", tendency: ["b"] },
    BombsiteA: { cn: "A包", tendency: ["a"] },
    Apartments: { cn: "二楼", tendency: ["a"] },
    Middle: { cn: "中路", tendency: ["mid"] },
    CTSpawn: { cn: "警家" },
    TopofMid: { cn: "中路", tendency: ["mid"] },
    Arch: { cn: "拱门", tendency: ["a"] },
    Ruins: { cn: "警家教堂", tendency: ["b"] },
    Pit: { cn: "大坑", tendency: ["a"] },
    SecondMid: { cn: "侧道", tendency: ["mid", "a"] },
    TRamp: { cn: "匪口", tendency: ["mid", "b"] },
    TSpawn: { cn: "匪家" },
    Balcony: { cn: "阳台", tendency: ["a"] },
    LowerMid: { cn: "匪口", tendency: ["mid", "b"] },
    Library: { cn: "书房", tendency: ["a"] },
    BackAlley: { cn: "匪二楼", tendency: ["a"] },
    Underpass: { cn: "下水道", tendency: ["mid"] },
    Quad: { cn: "马棚", tendency: ["a"] },
    Deck: { cn: "匪二阳台", },
    Bridge: { cn: "匪桥", tendency: ["mid", "a"] },
    Upstairs: { cn: "匪二楼", tendency: ["mid", "a"] },
    Graveyard: { cn: "墓地", tendency: ["a"] },
    Kitchen: { cn: "厨房", },
  },

  de_mirage: {
    BombsiteA: { cn: "A包", tendency: ["a"] },
    CTSpawn: { cn: "警家" },
    BombsiteB: { cn: "B包", tendency: ["b"] },
    PalaceInterior: { cn: "A二楼", tendency: ["a"] },
    Middle: { cn: "中路", tendency: ["mid"] },
    TopofMid: { cn: "中远/匪口", tendency: ["mid"] },
    Catwalk: { cn: "B小", tendency: ["b"] },
    Apartments: { cn: "B二楼", tendency: ["b"] },
    Underpass: { cn: "下水道", tendency: ["mid", "b"] },
    TSpawn: { cn: "匪家" },
    PalaceAlley: { cn: "A1", tendency: ["a"] },
    Connector: { cn: "拱门", tendency: ["a", "mid"] },
    SideAlley: { cn: "匪口", tendency: ["mid"] },
    BackAlley: { cn: "B二楼", tendency: ["b"] },
    Jungle: { cn: "Jungle", tendency: ["a"] },
    Shop: { cn: "超市", tendency: ["b"] },
    TRamp: { cn: "A1", tendency: ["a"] },
    SnipersNest: { cn: "VIP", tendency: ["mid"] },
    Truck: { cn: "白车", tendency: ["b"] },
    House: { cn: "匪二楼", tendency: ["b"] },
    Stairs: { cn: "跳台", tendency: ["a"] },
    Ladder: { cn: "黑屋", tendency: ["mid", "b"] },
    Scaffolding: { cn: "A2上下", tendency: ["a"] },
  },

  de_nuke: {
    Outside: { cn: "外场", tendency: ["mid"] },
    BombsiteA: { cn: "A包", tendency: ["a"] },
    Ramp: { cn: "铁板", tendency: ["b"] },
    Lobby: { cn: "匪厅", tendency: ["a"] },
    Tunnels: { cn: "K1地下", tendency: ["b"] },
    BombsiteB: { cn: "B包", tendency: ["b"] },
    TSpawn: { cn: "匪家" },
    Mini: { cn: "正门", tendency: ["a", "mid"] },
    Squeaky: { cn: "铁门房", tendency: ["a"] },
    Control: { cn: "链接", tendency: ["b"] },
    Garage: { cn: "大仓", tendency: ["mid"] },
    Rafters: { cn: "三楼横梁", tendency: ["a"] },
    Hut: { cn: "黄房", tendency: ["a"] },
    Vending: { cn: "链接", tendency: ["b"] },
    Heaven: { cn: "三楼", tendency: ["a"] },
    Admin: { cn: "铁板三楼下", tendency: ["b"] },
    CTSpawn: { cn: "警家" },
    Secret: { cn: "K1", tendency: ["b", "mid"] },
    Trophy: { cn: "奖杯房", tendency: ["b"] },
    HutRoof: { cn: "黄房顶", tendency: ["a"] },
    Hell: { cn: "三楼下", tendency: ["a", "b", "mid"] },
    Roof: { cn: "屋顶", tendency: ["a"] },
    Silo: { cn: "山上", tendency: ["mid"] },
    Vents: { cn: "管道", tendency: ["b"] },
    Catwalk: { cn: "外场三楼", tendency: ["mid"] },
    Decon: { cn: "死门", tendency: ["b"] },
    Crane: { cn: "A包柱上", tendency: ["a"] },
    Observation: { cn: "控制室", tendency: ["b"] },
    LockerRoom: { cn: "更衣室", tendency: ["mid"] },
  },

  de_overpass: {
    LowerPark: { cn: "A小厕所", tendency: ["a"] },
    Water: { cn: "工地", tendency: ["b"] },
    BombsiteA: { cn: "A包", tendency: ["a"] },
    BombsiteB: { cn: "B包", tendency: ["b"] },
    UpperPark: { cn: "A大厕所", tendency: ["a"] },
    Canal: { cn: "长管", tendency: ["b"] },
    Fountain: { cn: "喷泉", tendency: ["a"] },
    Tunnels: { cn: "下水道", tendency: ["mid"] },
    Connector: { cn: "下水道", tendency: ["mid", "a"] },
    Walkway: { cn: "ABC", tendency: ["b"] },
    Construction: { cn: "B小", tendency: ["b"] },
    TSpawn: { cn: "匪家" },
    Alley: { cn: "匪家B外", tendency: ["b"] },
    SnipersNest: { cn: "B二楼", tendency: ["b"] },
    UnderA: { cn: "一层", tendency: ["b"] },
    BackofA: { cn: "垃圾桶", tendency: ["a"] },
    Pipe: { cn: "短管", tendency: ["b"] },
    Lobby: { cn: "银行", tendency: ["a"] },
    Playground: { cn: "游乐园", tendency: ["a"] },
    Restroom: { cn: "厕所", tendency: ["a"] },
    TStairs: { cn: "匪楼梯" },
    Bridge: { cn: "桥", tendency: ["b"] },
    Stairs: { cn: "楼梯", tendency: ["a"] },
    StorageRoom: { cn: "银行", tendency: ["a"] },
    SideAlley: { cn: "匪家保枪位" },
  },
};

/** 所有已标定的地图名。 */
export const CALLOUT_MAPS = Object.keys(CALLOUT_DICT) as ReadonlyArray<string>;
