import type { RRIndicators } from "@rivalhub/rival-rating";
import { z } from "zod";

const clutchSplitSchema = z.object({
  count: z.number().int().nonnegative(),
  won: z.number().int().nonnegative()
});

export const rrIndicatorsSchema: z.ZodType<RRIndicators> = z.object({
  steamId64: z.string(),
  totalRounds: z.number().int().nonnegative(),
  kills: z.number().int().nonnegative(),
  deaths: z.number().int().nonnegative(),
  assists: z.number().int().nonnegative(),
  kpr: z.number().nonnegative(),
  dpr: z.number().nonnegative(),
  apr: z.number().nonnegative(),
  adr: z.number().nonnegative(),
  hsPercent: z.number().min(0).max(100),
  kast: z.number().min(0).max(100),
  survivalRate: z.number().min(0).max(1),
  twoKillRounds: z.number().int().nonnegative(),
  threeKillRounds: z.number().int().nonnegative(),
  fourKillRounds: z.number().int().nonnegative(),
  fiveKillRounds: z.number().int().nonnegative(),
  multiKillRate: z.number().min(0).max(1),
  firstKillCount: z.number().int().nonnegative(),
  firstDeathCount: z.number().int().nonnegative(),
  firstKillRate: z.number().nonnegative(),
  firstDeathRate: z.number().nonnegative(),
  openingDuelRate: z.number().nonnegative(),
  openingDuelWinRate: z.number().min(0).max(1),
  tradeKillCount: z.number().int().nonnegative(),
  tradeDeathCount: z.number().int().nonnegative(),
  tradeKillRate: z.number().nonnegative(),
  tradeDeathRate: z.number().nonnegative(),
  clutchAttempts: z.number().int().nonnegative(),
  clutchWins: z.number().int().nonnegative(),
  clutchWinRate: z.number().min(0).max(1),
  clutchFrequency: z.number().nonnegative(),
  clutchScore: z.number().nonnegative(),
  clutchScoreRate: z.number().nonnegative(),
  vsOne: clutchSplitSchema,
  vsTwo: clutchSplitSchema,
  vsThree: clutchSplitSchema,
  vsFour: clutchSplitSchema,
  vsFive: clutchSplitSchema,
  awpKills: z.number().int().nonnegative(),
  awpKillsPerRound: z.number().nonnegative(),
  awpKillRate: z.number().min(0).max(1),
  sniperKills: z.number().int().nonnegative(),
  sniperKillRate: z.number().min(0).max(1),
  awpMultiKillRate: z.number().min(0).max(1).nullable(),
  awpDuelWinRate: z.number().min(0).max(1).nullable(),
  utilityDamage: z.number().int().nonnegative(),
  utilityDamagePerRound: z.number().nonnegative(),
  flashAssistCount: z.number().int().nonnegative(),
  flashAssistPerRound: z.number().nonnegative(),
  blindDurationTotal: z.number().nonnegative(),
  blindDurationPerRound: z.number().nonnegative(),
  enemyFlashDurationSeconds: z.number().nonnegative().nullable(),
  enemyFlashDurationPerRound: z.number().nonnegative().nullable(),
  teamFlashDurationSeconds: z.number().nonnegative().nullable(),
  teamFlashDurationPerRound: z.number().nonnegative().nullable(),
  grenadeCount: z.number().int().nonnegative(),
  grenadeCountPerRound: z.number().nonnegative(),
  ecoRoundCount: z.number().int().nonnegative(),
  forceRoundCount: z.number().int().nonnegative(),
  fullBuyRoundCount: z.number().int().nonnegative(),
  pistolRoundCount: z.number().int().nonnegative(),
  avgEquipmentValue: z.number().nonnegative(),
  combatDeathCount: z.number().int().nonnegative().nullable(),
  bombDeathCount: z.number().int().nonnegative().nullable(),
  wallbangKillCount: z.number().int().nonnegative().nullable(),
  roundSwingTotal: z.number().nullable(),
  roundSwingPerKill: z.number().nullable()
});

export type { AccountSignalsV2, RRIndicators, RRResult, RRResultV2, PrismResult, ValueAccountsWeights } from "@rivalhub/rival-rating";
